name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build config'
        required: true
        type: choice
        default: Release
        options:
          - Debug
          - Release

jobs:
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      buildType: ${{steps.assign_build_input.outputs.buildType}}
    steps:
      - name: Check buildType Input
        id: assign_build_input
        run: echo "buildType=${{(github.event.inputs.buildType||'Release')}}" >> $GITHUB_OUTPUT

      - name: Validate Inputs
        id: check_input_vals
        run: echo "{buildType:'${{github.event.inputs.buildType}}'}"

      - name: Validate Outputs
        id: check_output_vals
        run: echo "{buildType:'${{steps.assign_build_input.outputs.buildType}}'}"

  build-ubuntu-latest:
    needs: [env-setup]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: ubuntu-latest
      buildType: ${{needs.env-setup.outputs.buildType}}

  build-windows-latest:
    needs: [env-setup]
    uses: ./.github/workflows/cmake.yml
    with:
      platform: windows-latest
      buildType: ${{needs.env-setup.outputs.buildType}}
