name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    buildType:
      description: 'Build config'
      required: true
      default: 'Release'
      type: choice
      options:
        - Debug
        - Release
    branch:
      description: 'Target branch to build'
      default: 'master'
      required: false
      type: string

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: ./.github/workflows/cmake.yml
        with:
          platform: ${{matrix.os}}
          branch: ${{inputs.branch}}
          buildType: ${{inputs.buildType}}
