name: windows-installer

on:
  workflow_run:
    workflows:
      - "CMake"
    branches:
      - "master"
    tags:
      - "v.*-stable"
    types:
      - "completed"
    conclusion:
      - "success"
jobs:
  make-installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@v3
        with:
          name: hobovr-build-windows-latest
          path: ${{ github.workspace }}

      - name: Extract Driver
        run: 7z x "${{ github.workspace }}\hobovr-build-windows-latest.zip" -o"${{ github.workspace }}/hobovr" -r -y

      - name: Download ExecDos plugin
        uses: carlosperate/download-file-action@v1.1.1
        with:
          file-url: "https://nsis.sourceforge.io/mediawiki/images/0/0f/ExecDos.zip"
          file-name: "ExecDos.zip"
          location: "${{ github.workspace }}"
          sha256: "a90f00e117f961f97a87d25484e196edb407cb6778c2f0891350bcab97027b74"

      - name: Extract ExecDos plugin
        run: 7z x "${{ github.workspace }}/ExecDos.zip" -o"${{ github.workspace }}/NSIS" "Plugins/*" -r -y

      - name: Download Registry plugin
        uses: carlosperate/download-file-action@v1.1.1
        with:
          file-url: "https://nsis.sourceforge.io/mediawiki/images/4/47/Registry.zip"
          file-name: "Registry.zip"
          location: "${{ github.workspace }}"
          sha256: "8951a152e1b6addbe2fee953795a992625e860d893b22f928cbf2750c66d6e76"

      - name: Extract Registry plugin
        run: 7z e "${{ github.workspace }}/Registry.zip" -o"${{ github.workspace }}/NSIS/Plugins" "Desktop/Plugin/*" -y

      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: ${{ github.workspace }}/installers/win/hobovr_installer.nsi
          additional-plugin-paths: ${{ github.workspace }}/NSIS/Plugins

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "hobovr_setup.exe"
          path: |
            hobovr